version: '3'

networks:
  my_network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
